version: 2.1
orbs:
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1
jobs:
  client:
    docker:
      - image: "cimg/node:14.15"
    steps:
      - node/install:
          node-version: '14.15'         
      - checkout
      - run:
          name: Install Front-End Dependencies
          command: |
            npm run install:client
      - run:
          name: Build Front-End App
          command: |
            npm run build:client   
      - aws-cli/setup
      - run:
          name: Deploy Front-End App
          command: |
            npm run deploy:client
  api:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install:
          node-version: '14.15'         
      - checkout 
      - run:
          name: Install API Dependencies
          command: |
            npm run install:server
      - run:
          name: Build API
          command: |
            npm run build:server
      - eb/setup
      - aws-cli/setup
      - run:
          name: Deploy API
          command: |
            aws s3 cp ./Storefront-API/Archive.zip s3://storefront-hassan/
            aws elasticbeanstalk create-application-version --application-name "storefront api" --version-label <<pipeline.git.revision>> --source-bundle S3Bucket="storefront-hassan",S3Key="Archive.zip"
            aws elasticbeanstalk update-environment --application-name "storefront api" --environment-name "Storefrontapi-env-1" --version-label <<pipeline.git.revision>> --option-settings Namespace=aws:elasticbeanstalk:application:environment,OptionName=NODE_ENV,Value="producion" Namespace=aws:elasticbeanstalk:application:environment,OptionName=DATABASE_HOST,Value=$DATABASE_HOST Namespace=aws:elasticbeanstalk:application:environment,OptionName=DATABASE_PORT,Value=$DATABASE_PORT Namespace=aws:elasticbeanstalk:application:environment,OptionName=DATABASE_NAME,Value=$DATABASE_NAME Namespace=aws:elasticbeanstalk:application:environment,OptionName=TEST_DATABASE_NAME,Value=$DATABASE_NAME Namespace=aws:elasticbeanstalk:application:environment,OptionName=DATABASE_USER,Value=$DATABASE_USER Namespace=aws:elasticbeanstalk:application:environment,OptionName=DATABASE_PASSWORD,Value=$DATABASE_PASSWORD Namespace=aws:elasticbeanstalk:application:environment,OptionName=JWT_SECRET, Value=$JWT_SECRET Namespace=aws:elasticbeanstalk:application:environment,OptionName=BCRYPT_SECRET,Value=$BCRYPT_SECRET Namespace=aws:elasticbeanstalk:application:environment,OptionName=BCRYPT_SALT,Value=$BCRYPT_SALT
            
workflows:
  Storefront:
    jobs:
      - client:
          filters:
            branches:
              only:
                - main
      - api:
          filters:
            branches:
              only:
                - main
